version: 2

sources:
  - name: snowflake
    database: stockllm
    schema: raw_data
    description: Staging Step Proceeding Raw data from snowflake
    
    tables:
      - name: countries
        description: Countries name and ISO Alpha 2 and ISO Alpha 3 code 
        config:
          meta:
            field: general 
            group: country
        
        columns:
          - name: name 
            description: country name 
            data_tests:
              - not_null
              - unique 
            
          - name: iso_alpha_2_code
            description: country ISO Alpha 2 code 
            data_tests:
              - not_null
          
          - name: iso_alpha_3_code
            description: country ISO Alpha 3 code 
            data_tests:
              - not_null     
              

      - name: imf_nominal_gdp
        description: International Nominal GDP
        config:
          meta:
            field: macro
            group: gdp 

        columns:
          - name: country
            description: Countries name 
            data_tests:
              - not_null
              - relationships:
                  arguments: 
                    to: source('snowflake', 'countries')
                    field: name
            
          - name: year
            description: time when data is available  
            data_tests:
              - not_null
            
          - name: type
            description: projection or history data  
            data_tests:
              - not_null
              - accepted_values:
                  arguments: 
                    values: ['History', 'Projection']
      
          - name: gdp_growth_pct
            description: nominal gdp growth rate in %
            data_tests:
              - not_null
          
          - name: gdp_per_capita_usd
            description: nominal gdp per capita in usd 
            data_tests:
              - not_null
            
          - name: gdp_nominal_usd
            description: nominal gdp in usd
            data_tests:
              - not_null

          - name: population_change_pct
            description: population change in %
            data_tests:
              - not_null

      - name: imf_ppp_gdp
        description: International power purchase parity gdp
        config:
          meta:
            field: macro
            group: gdp 

        columns:
          - name: country
            description: Countries name 
            data_tests:
              - not_null
              - relationships:
                  arguments: 
                    to: source('snowflake', 'countries')
                    field: name
            
          - name: year
            description: time when data is available 
            data_tests:
              - not_null
            
          - name: type
            description: projection or history data  
            data_tests:
              - not_null
              - accepted_values:
                  arguments: 
                    values: ['History', 'Projection']
      
          - name: gdp_ppp_growth_pct
            description: ppp gdp growth rate in %
            data_tests:
              - not_null
          
          - name: gdp_ppp_per_capita_usd
            description: ppp gdp per capita in usd 
            data_tests:
              - not_null
            
          - name: gdp_ppp_usd
            description: ppp gdp in usd
            data_tests:
              - not_null

          - name: population_change_pct
            description: population change in %
            data_tests:
              - not_null

      - name: wb_gdp
        description: world bank gdp 
        config:
          meta:
            field: macro
            group: gdp
          
        columns:
          - name: country
            description: country name 
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('snowflake', 'countries')
                    field: name
          
          - name: type
            description: History or Projection data 
            data_tests:
              - not_null
              - accepted_values:
                  arguments:
                    values: ['History', 'Projection']
              
          - name: year 
            description: time when data is available 
            data_tests:
              - not_null
            
          - name: gdp_nominal_usd
            description: nominal gdp in usd 
            data_tests:
              - not_null

          - name: gdp_real_usd
            description: real gdp in usd 
            data_tests:
              - not_null
          
          - name: population_change_pct
            description: population change in %
            data_tests:
              - not_null
              
              
            

          

                         
                

